version: '2.4'

services:
  pgdb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=pguser
      - POSTGRES_DB=crypto-exchange
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-cache:
    image: redis:6
    container_name: in_memory_redis_cache
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
